#lang sicp
(define (cont-frac n d k)
  (define (iter i)
    (if (= i k)
        (/ (n k) (d k))
        (/ (n i) (+ (d i) (iter (+ i 1))))
        )
    )
  (iter 1)
  )

(define (cont-frac-loop n d k)
  (define (iter ret i)
    (if (= i 1)
        (/ (n 1) (+ (d 1) ret))
        (iter ()
              (- i 1)
              )
        )
    )
  (iter (/ (n k) (d k)) (- k 1))
  )